services:
  coupon-service:
    build: .
    container_name: coupon-service
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app
    environment:
      - FLASK_ENV=development
      - MONGO_URI=mongodb://mongo-db:27017/coupon_db
    depends_on:
      - mongo-db

  mongo-db:
    image: mongo:6.0
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
